"""Explicit limits for Coding Slice C1 structured tools."""

from __future__ import annotations

import re

MAX_TOOLS_PER_REQUEST = 16
MAX_TOOL_NAME_LENGTH = 64
TOOL_NAME_PATTERN = re.compile(r"^[a-zA-Z][a-zA-Z0-9_]*$")
MAX_TOOL_DESCRIPTION_LENGTH = 2_000
MAX_SCHEMA_SERIALIZED_BYTES = 16 * 1024
MAX_SCHEMA_NESTING_DEPTH = 8
MAX_TOOL_CALL_INPUT_BYTES = 8 * 1024
MAX_TOOL_RESULT_CONTENT_BYTES = 64 * 1024
MAX_TOOL_ROUNDS_IN_REQUEST = 8
MAX_ASSISTANT_TOOL_CALLS_PER_TURN = 1
